apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: pgdb
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgdb
spec:
  serviceName: pgdb
  selector:
    matchLabels:
      app: pgdb
  replicas: 2
  template:
    metadata:
      labels:
        app: pgdb
    spec:
      containers:
        - name: pgdb
          image: postgres:12.4
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: 5432
          envFrom:
          - configMapRef:
              name: postgres-config
          volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: example-claim
---
apiVersion: v1
kind: Service
metadata:
  name: pgdb
  labels:
    app: pgdb
spec:
  type: NodePort
  selector:
    app: pgdb
  ports:
    - protocol: TCP
      name: http
      port: 5432
      targetPort: 5432
      nodePort: 30008
